[package]
name = "cryptopals"
version = "0.1.0"
authors = ["Mariano Casco <marianoc88@gmail.com>"]
edition = "2018"

[dependencies]
aes = "0.8"

[[bin]]
name = "set1"
path = "src/set1.rs"

[[bin]]
name = "set2"
path = "src/set2.rs"