[package]
name = "cryptopals"
version = "0.1.0"
authors = ["Mariano Casco <marianoc88@gmail.com>"]
edition = "2018"

[dependencies]
aes = "0.8"
log = "0.4.0"
env_logger = "0.8.4"
anyhow = "1.0"


[[bin]]
name = "set1"
path = "src/bin/set1.rs"

[[bin]]
name = "set2"
path = "src/bin/set2.rs"
